apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: sonicexe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: sonicexe/go-helloworld-2
        name: go-helloworld-2
